package Modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 05-jul-2018 4:01:11 by Hibernate Tools 3.4.0.CR1

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="Administrador")

public class Administrador implements java.io.Serializable {
	
	@Id
	@Column(name="email")
	private String email;
	
	@Column(name="contraseña")
	private String contraseña;

	public Administrador() {
	}

	public Administrador(String email, String contraseña) {
		this.email = email;
		this.contraseña = contraseña;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(String contraseña) {
		this.contraseña = contraseña;
	}

}
