package Modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 05-jul-2018 4:01:11 by Hibernate Tools 3.4.0.CR1

/**
 * Cliente generated by hbm2java
 */

@Entity
@Table(name="Cliente")
public class Cliente implements java.io.Serializable {
	
	@Id
	@Column(name="email")
	private String email;
	
	@Column(name="nombre")
	private String nombre;
	
	@Column(name="apellidos")
	private String apellidos;
	
	@Column(name="dni")
	private String dni;
	
	@Column(name="direccion")
	private String dirección;
	
	@Column(name="contraseña")
	private String contraseña;
	
	@Column(name="telefono")
	private String telefono;

	public Cliente() {
	}

	public Cliente(String email, String nombre, String apellidos, String dni,
			String dirección, String contraseña) {
		this.email = email;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.dirección = dirección;
		this.contraseña = contraseña;
	}

	public Cliente(String email, String nombre, String apellidos, String dni,
			String dirección, String contraseña, String telefono) {
		this.email = email;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.dirección = dirección;
		this.contraseña = contraseña;
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getDirección() {
		return this.dirección;
	}

	public void setDirección(String dirección) {
		this.dirección = dirección;
	}

	public String getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(String contraseña) {
		this.contraseña = contraseña;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
