package Modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 05-jul-2018 4:01:11 by Hibernate Tools 3.4.0.CR1

/**
 * Ofertas generated by hbm2java
 */

@Entity
@Table(name="Ofertas")
public class Ofertas implements java.io.Serializable {

	@Id	
	@Column(name="tipo")
	private String tipo;
	
	@Column(name="precio")
	private String precio;
	
	@Column(name="descuento")
	private String descuento;

	public Ofertas() {
	}

	public Ofertas(String tipo, String precio, String descuento) {
		this.tipo = tipo;
		this.precio = precio;
		this.descuento = descuento;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getPrecio() {
		return this.precio;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

	public String getDescuento() {
		return this.descuento;
	}

	public void setDescuento(String descuento) {
		this.descuento = descuento;
	}

}
