package Modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 05-jul-2018 4:01:11 by Hibernate Tools 3.4.0.CR1

/**
 * Productos generated by hbm2java
 */

@Entity
@Table(name="Productos")
public class Productos implements java.io.Serializable {

	@Id
	@Column(name="nombre")
	private String nombre;
	
	@Column(name="precio")
	private String precio;
	
	@Column(name="stock")
	private int stock;

	public Productos() {
	}

	public Productos(String nombre, String precio, int stock) {
		this.nombre = nombre;
		this.precio = precio;
		this.stock = stock;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPrecio() {
		return this.precio;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

}
